objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Web_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Web Order</label>
        <referenceTo>Web_Order__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Web_Order__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Web Orders</relationshipLabel>
        <relationshipName>Web_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Prospecting</fullName>
                </value>
                <value>
                    <fullName>Qualification</fullName>
                </value>
                <value>
                    <fullName>Needs Analysis</fullName>
                </value>
                <value>
                    <fullName>Value Proposition</fullName>
                </value>
                <value>
                    <fullName>Id. Decision Makers</fullName>
                </value>
                <value>
                    <fullName>Perception Analysis</fullName>
                </value>
                <value>
                    <fullName>Proposal/Price Quote</fullName>
                </value>
                <value>
                    <fullName>Negotiation/Review</fullName>
                </value>
                <value>
                    <fullName>Closed Won</fullName>
                </value>
                <value>
                    <fullName>Closed Lost</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Web Order</label>
    <nameField>
        <label>Web Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Web Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/WebOrderTriggerHandler.cls
public class WebOrderTriggerHandler {
    public static void handleTrigger(List<Web_Order__c> newWebOrders, List<Web_Order__c> oldWebOrders, System.TriggerOperation triggerEvent) {
        switch on triggerEvent {
            when BEFORE_DELETE {

            }
            when AFTER_INSERT {

                List<Opportunity> opportunities = new List<Opportunity>();
                for (Web_Order__c currentWebOrder : newWebOrders) {
                    opportunities.add(new Opportunity(
                            Name = currentWebOrder.Name,
                            AccountId = currentWebOrder.Account__c,
                            StageName = currentWebOrder.Status__c,
                            CloseDate = Date.today().addDays(30),
                            Web_Order__c = currentWebOrder.Id
                    ));
                }

                try {
                    insert opportunities;
                } catch (DmlException e) {}

                Map<Id, Web_Order__c> webOrders = new Map<Id, Web_Order__c>(newWebOrders);
                List<Quote> quotes = new List<Quote>();
                for (Opportunity currentOpportunity : opportunities) {
                    quotes.add(new Quote(
                            Name = currentOpportunity.Name + 'Quote',
                            OpportunityId = currentOpportunity.Id,
                            Country__c = webOrders.get(currentOpportunity.Web_Order__c).Country__c,
                            City__c = webOrders.get(currentOpportunity.Web_Order__c).City__c,
                            Street__c = webOrders.get(currentOpportunity.Web_Order__c).Street__c
                    ));
                }

                try {
                    insert quotes;
                } catch (DmlException e) {}

                Map<Id, Id> OpportunityIdsToQuoteIds = new Map<Id, Id>();
                for (Quote currentQuote : quotes) {
                    OpportunityIdsToQuoteIds.put(currentQuote.OpportunityId, currentQuote.Id);
                }

                TriggerHelper.updateOpportunity(OpportunityIdsToQuoteIds);
            }
            when AFTER_UPDATE {

                List<Quote> quotes = [
                        SELECT
                                Opportunity.Web_Order__r.Country__c,
                                Opportunity.Web_Order__r.City__c,
                                Opportunity.Web_Order__r.Street__c
                        FROM Quote
                        WHERE Opportunity.Web_Order__c IN :newWebOrders
                ];

                for (Quote currentQuote : quotes) {
                    currentQuote.Country__c = currentQuote.Opportunity.Web_Order__r.Country__c;
                    currentQuote.City__c = currentQuote.Opportunity.Web_Order__r.City__c;
                    currentQuote.Street__c = currentQuote.Opportunity.Web_Order__r.Street__c;
                }

                try {
                    update quotes;
                } catch (DmlException e) {}
            }
        }
    }
}