objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Web_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Web Order</label>
        <referenceTo>Web_Order__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Web_Order__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Web Orders</relationshipLabel>
        <relationshipName>Web_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Prospecting</fullName>
                </value>
                <value>
                    <fullName>Qualification</fullName>
                </value>
                <value>
                    <fullName>Needs Analysis</fullName>
                </value>
                <value>
                    <fullName>Value Proposition</fullName>
                </value>
                <value>
                    <fullName>Id. Decision Makers</fullName>
                </value>
                <value>
                    <fullName>Perception Analysis</fullName>
                </value>
                <value>
                    <fullName>Proposal/Price Quote</fullName>
                </value>
                <value>
                    <fullName>Negotiation/Review</fullName>
                </value>
                <value>
                    <fullName>Closed Won</fullName>
                </value>
                <value>
                    <fullName>Closed Lost</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Web Order</label>
    <nameField>
        <label>Web Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Web Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OpportunityTriggerHandler.cls
/*********************************************************************************************
* Purpose:
* --------
* Encapsulate Opportunity-related business functions.
* To be called from the Opportunity.trigger
*
* TestClasses:
* ------------
* - OpportunityTriggerHandlerTest.cls
*
* History:
* --------
* VERSION  CHANGE DATE  AUTHOR              VERSION COMMENTS / Release Task
* 1.0      2018-11-15   Pavel Makarets      Initial Version
*********************************************************************************************/

public class OpportunityTriggerHandler {
    public static void handleTrigger(List<Opportunity> newOpportunities, List<Opportunity> oldOpportunities, System.TriggerOperation triggerEvent) {
        switch on triggerEvent {
            when BEFORE_DELETE {

                try {
                    delete [SELECT Id, (SELECT Id FROM Opportunities__r Opportunities WHERE Id IN :oldOpportunities) FROM Web_Order__c];
                } catch (DmlException e) {}

            }
            when BEFORE_INSERT {

                List<Web_Order__c> webOrders = new List<Web_Order__c>();
                for (Opportunity currentOpportunity : newOpportunities) {
                    webOrders.add(new Web_Order__c(
                            Name = currentOpportunity.Name,
                            Account__c = currentOpportunity.AccountId,
                            Status__c = currentOpportunity.StageName
                    ));
                }

                try {
                    insert webOrders;
                } catch (DmlException e) {}

                for (Opportunity currentOpportunity : newOpportunities) {
                    for (Web_Order__c currentWebOrder : webOrders) {
                        currentOpportunity.Web_Order__c = currentWebOrder.Id;
                    }
                }

            }
        }
    }
}